pr: none
trigger:
  batch: false
  branches:
    include:
    - develop
  paths:
    include:
    - Intelliworks.Pms.AzureDeploy/Bicep/Infrastructure/*

variables:
  major: 1
  minor: 0
  patch: $[counter(format('{0}.{1}-{2}', variables['major'], variables['minor'], variables['Build.SourceBranchName']), 1)]
  ${{ if eq( variables['Build.SourceBranchName'], 'main' ) }}: 
    branch: ''
  ${{ if ne( variables['Build.SourceBranchName'], 'main' ) }}: 
    branch: -${{ variables['Build.SourceBranchName'] }}

name: $(major).$(minor).$(patch)$(branch)

pool:
  vmImage: ubuntu-latest

stages:
### Validate & Publish
- template: ../Templates/Stages/stage-validate-publish-bicep.yml
  parameters:
    name: Validate_Publish
    displayName: Validate & Publish
    variables:
    - template: ../Variables/variables-global.yml

### Deploy Infrastructure BVT
- template: ../Templates/Stages/stage-deploy-infrastructure.yml
  parameters:
    name: Deploy_Infrastructure_BVT
    displayName: Deploy Infrastructure BVT
    dependsOn: Validate_Publish
    variables:
    - template: ../Variables/variables-global.yml
    - template: ../Variables/variables-bvt.yml
    environment: BVT