trigger:
- main

name: Deploy Bicep files

variables:
  vmImageName: 'ubuntu-latest'

  azureServiceConnection: '<FA-conn>'
  resourceGroupName: 'Test'
  location: "East US"
  templateFile: './main.bicep'
pool:
  vmImage: "ubuntu-latest"

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: "FA-conn"
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    overrideParameters: '-storageAccountType Standard_LRS'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

- task: AzureCLI@2
  inputs:
    azureSubscription: "FA-conn"
    scriptType: bash
    scriptLocation: inlineScript
    useGlobalConfig: false
    inlineScript: |
      az --version
      az deployment group create --resource-group "East US" --template-file $(templateFile)