trigger:
- main

pr:
- none

jobs:
- job: DeployResourceGroup
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
      checkLatest: true
 

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Functest'  # Replace with your Azure service connection name
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az login --service-principal -u $AZURE_CLIENT_ID -p "$AZURE_CLIENT_SECRET" --tenant $AZURE_TENANT_ID
        az deployment group create --resource-group 'Intelliworks-Pms-bvt-uks' --template-file 'Bicep\Infra\main.bicep' --parameters 'Bicep\Infra\main.bicep.parameters.json'